env: "local"
storage_path: "./storage.db"
http_server:
  host: "localhost"
  port: "1337"
  timeout: 4s
  idle_timeout: 30s
db:
  driver: "postgres"
  name: "schedule"
  port: "5432"
  user: ""
  password: ""
kafka:
  host: "localhost"
  port: "9092"



